version: "3.9" #optional since v1.27.0
services:
  mysql:
    image: mysql
    container_name: seminario_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  web:
    build: .
    ports:
      - "80:80"
    